//! ScreenCaptureKit capture of the main display: NV12 frames with the cursor composited in, plus
//! the dirty rects SCK attaches to every sample buffer.

use std::ffi::c_void;
use std::panic::{catch_unwind, AssertUnwindSafe};
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::{mpsc, Arc, Mutex};
use std::time::Duration;

use agent_snap_core::platform::{CaptureInfo, Frame, RectI, ScreenCapture};
use anyhow::{anyhow, bail, Context, Result};
use block2::RcBlock;
use dispatch2::{DispatchQueue, DispatchQueueAttr, DispatchRetained};
use objc2::rc::Retained;
use objc2::runtime::ProtocolObject;
use objc2::{define_class, msg_send, AnyThread, DefinedClass};
use objc2_core_foundation::{CFArray, CFDictionary, CFNumber, CGPoint, CGRect, CGSize};
use objc2_core_graphics::{CGDisplayPixelsWide, CGMainDisplayID, CGRectMakeWithDictionaryRepresentation};
use objc2_core_media::{CMSampleBuffer, CMTime};
use objc2_core_video::{kCVPixelFormatType_420YpCbCr8BiPlanarFullRange, kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange};
use objc2_foundation::{NSArray, NSError, NSObject, NSObjectProtocol, NSString};
use objc2_screen_capture_kit::{
    SCContentFilter, SCDisplay, SCFrameStatus, SCShareableContent, SCStream, SCStreamConfiguration,
    SCStreamDelegate, SCStreamFrameInfoDirtyRects, SCStreamFrameInfoStatus, SCStreamOutput, SCStreamOutputType,
};

use crate::util::{cf_number_i64, instant_from_host_time, SendCell};

// The plane accessors are not generated by objc2-core-video; declare the handful we need.
#[link(name = "CoreVideo", kind = "framework")]
extern "C" {
    fn CVPixelBufferLockBaseAddress(pb: *const c_void, flags: u64) -> i32;
    fn CVPixelBufferUnlockBaseAddress(pb: *const c_void, flags: u64) -> i32;
    fn CVPixelBufferGetPixelFormatType(pb: *const c_void) -> u32;
    fn CVPixelBufferGetWidth(pb: *const c_void) -> usize;
    fn CVPixelBufferGetHeight(pb: *const c_void) -> usize;
    fn CVPixelBufferGetPlaneCount(pb: *const c_void) -> usize;
    fn CVPixelBufferGetBaseAddressOfPlane(pb: *const c_void, plane: usize) -> *const u8;
    fn CVPixelBufferGetBytesPerRowOfPlane(pb: *const c_void, plane: usize) -> usize;
    fn CVPixelBufferGetHeightOfPlane(pb: *const c_void, plane: usize) -> usize;
}
const CV_LOCK_READ_ONLY: u64 = 1;

type FrameCallback = Box<dyn FnMut(Frame) + Send>;
type Planes = (Arc<[u8]>, Arc<[u8]>);

struct OutputIvars {
    cb: Mutex<Option<FrameCallback>>,
    width: u32,
    height: u32,
    delivered: AtomicU64,
    skipped: AtomicU64,
    warned_format: AtomicBool,
}

define_class!(
    // SAFETY: NSObject has no subclassing requirements; StreamOutput does not implement Drop.
    #[unsafe(super(NSObject))]
    #[name = "AgentSnapStreamOutput"]
    #[ivars = OutputIvars]
    struct StreamOutput;

    unsafe impl NSObjectProtocol for StreamOutput {}

    unsafe impl SCStreamOutput for StreamOutput {
        #[unsafe(method(stream:didOutputSampleBuffer:ofType:))]
        #[allow(non_snake_case)]
        unsafe fn stream_didOutputSampleBuffer_ofType(
            &self,
            _stream: &SCStream,
            sample_buffer: &CMSampleBuffer,
            r#type: SCStreamOutputType,
        ) {
            if r#type != SCStreamOutputType::Screen {
                return;
            }
            // Never let a Rust panic unwind into ScreenCaptureKit.
            let _ = catch_unwind(AssertUnwindSafe(|| self.handle(sample_buffer)));
        }
    }

    unsafe impl SCStreamDelegate for StreamOutput {
        #[unsafe(method(stream:didStopWithError:))]
        #[allow(non_snake_case)]
        unsafe fn stream_didStopWithError(&self, _stream: &SCStream, error: &NSError) {
            log::warn!("capture stopped: {}", error.localizedDescription());
        }
    }
);

impl StreamOutput {
    fn new(width: u32, height: u32, cb: FrameCallback) -> Retained<Self> {
        let this = Self::alloc().set_ivars(OutputIvars {
            cb: Mutex::new(Some(cb)),
            width,
            height,
            delivered: AtomicU64::new(0),
            skipped: AtomicU64::new(0),
            warned_format: AtomicBool::new(false),
        });
        unsafe { msg_send![super(this), init] }
    }

    fn handle(&self, sb: &CMSampleBuffer) {
        let iv = self.ivars();
        let (w, h) = (iv.width, iv.height);

        // Frame status + dirty rects live in the first sample attachment dictionary.
        let Some(atts) = (unsafe { sb.sample_attachments_array(false) }) else { return };
        if atts.count() == 0 {
            return;
        }
        let dict = unsafe { atts.value_at_index(0) } as *const CFDictionary;
        if dict.is_null() {
            return;
        }
        let dict = unsafe { &*dict };

        let status_key = unsafe { SCStreamFrameInfoStatus } as *const NSString as *const c_void;
        let status = unsafe { dict.value(status_key) } as *const CFNumber;
        if status.is_null() {
            return;
        }
        let status = unsafe { &*status };
        if cf_number_i64(status) != Some(SCFrameStatus::Complete.0 as i64) {
            iv.skipped.fetch_add(1, Ordering::Relaxed);
            return;
        }

        let mut dirty: Vec<RectI> = Vec::new();
        let rects_key = unsafe { SCStreamFrameInfoDirtyRects } as *const NSString as *const c_void;
        let rects = unsafe { dict.value(rects_key) } as *const CFArray;
        if !rects.is_null() {
            let rects = unsafe { &*rects };
            for i in 0..rects.count() {
                let d = unsafe { rects.value_at_index(i) } as *const CFDictionary;
                if d.is_null() {
                    continue;
                }
                let mut r = CGRect::new(CGPoint::new(0.0, 0.0), CGSize::new(0.0, 0.0));
                if unsafe { CGRectMakeWithDictionaryRepresentation(Some(&*d), &mut r) } {
                    if let Some(c) = clamp_rect(r, w, h) {
                        dirty.push(c);
                    }
                }
            }
        }

        let pts: CMTime = unsafe { sb.presentation_time_stamp() };
        let t = instant_from_host_time(pts);

        let Some(pb) = (unsafe { sb.image_buffer() }) else { return };
        let pbp = objc2_core_foundation::CFRetained::as_ptr(&pb).as_ptr() as *const c_void;

        let fmt = unsafe { CVPixelBufferGetPixelFormatType(pbp) };
        if fmt != kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange && fmt != kCVPixelFormatType_420YpCbCr8BiPlanarFullRange {
            if !iv.warned_format.swap(true, Ordering::Relaxed) {
                log::warn!("unexpected pixel format 0x{fmt:08x}, frames dropped");
            }
            return;
        }

        if unsafe { CVPixelBufferLockBaseAddress(pbp, CV_LOCK_READ_ONLY) } != 0 {
            return;
        }
        let copied = unsafe { copy_planes(pbp, w, h) };
        unsafe { CVPixelBufferUnlockBaseAddress(pbp, CV_LOCK_READ_ONLY) };
        let Some((y, uv)) = copied else { return };

        let frame = Frame {
            t,
            width: w,
            height: h,
            y_stride: w as usize,
            uv_stride: w as usize,
            y,
            uv,
            dirty,
        };
        iv.delivered.fetch_add(1, Ordering::Relaxed);
        if let Ok(mut g) = iv.cb.lock() {
            if let Some(cb) = g.as_mut() {
                cb(frame);
            }
        }
    }
}

/// Copy Y and UV planes into tightly packed buffers (stride == width). Caller holds the lock.
unsafe fn copy_planes(pbp: *const c_void, w: u32, h: u32) -> Option<Planes> {
    if CVPixelBufferGetPlaneCount(pbp) < 2 {
        return None;
    }
    let src_w = CVPixelBufferGetWidth(pbp);
    let src_h = CVPixelBufferGetHeight(pbp);
    let (w, h) = (w as usize, h as usize);
    if src_w < w || src_h < h {
        return None;
    }
    let y_base = CVPixelBufferGetBaseAddressOfPlane(pbp, 0);
    let uv_base = CVPixelBufferGetBaseAddressOfPlane(pbp, 1);
    if y_base.is_null() || uv_base.is_null() {
        return None;
    }
    let y_stride = CVPixelBufferGetBytesPerRowOfPlane(pbp, 0);
    let uv_stride = CVPixelBufferGetBytesPerRowOfPlane(pbp, 1);
    let uv_rows = CVPixelBufferGetHeightOfPlane(pbp, 1).min(h.div_ceil(2));
    if y_stride < w || uv_stride < w {
        return None;
    }

    let mut y = Arc::<[u8]>::new_uninit_slice(w * h);
    {
        let dst = Arc::get_mut(&mut y).expect("fresh arc").as_mut_ptr() as *mut u8;
        for row in 0..h {
            std::ptr::copy_nonoverlapping(y_base.add(row * y_stride), dst.add(row * w), w);
        }
    }
    let uv_len = w * h.div_ceil(2);
    let mut uv = Arc::<[u8]>::new_uninit_slice(uv_len);
    {
        let dst = Arc::get_mut(&mut uv).expect("fresh arc").as_mut_ptr() as *mut u8;
        // Zero any rows beyond what the buffer holds (odd heights), then copy.
        std::ptr::write_bytes(dst, 128, uv_len);
        for row in 0..uv_rows {
            std::ptr::copy_nonoverlapping(uv_base.add(row * uv_stride), dst.add(row * w), w);
        }
    }
    Some((y.assume_init(), uv.assume_init()))
}

fn clamp_rect(r: CGRect, w: u32, h: u32) -> Option<RectI> {
    let x0 = r.origin.x.floor().max(0.0);
    let y0 = r.origin.y.floor().max(0.0);
    let x1 = (r.origin.x + r.size.width).ceil().min(w as f64);
    let y1 = (r.origin.y + r.size.height).ceil().min(h as f64);
    if !(x1 > x0 && y1 > y0) {
        return None;
    }
    Some(RectI { x: x0 as i32, y: y0 as i32, w: (x1 - x0) as i32, h: (y1 - y0) as i32 })
}

struct Inner {
    stream: Retained<SCStream>,
    output: Retained<StreamOutput>,
    _queue: DispatchRetained<DispatchQueue>,
}

/// ScreenCaptureKit-backed capture of the main display.
#[derive(Default)]
pub struct MacCapture {
    inner: Option<SendCell<Inner>>,
}

impl MacCapture {
    pub fn new() -> Self {
        Self::default()
    }

    /// (delivered, skipped-as-incomplete) counters since start.
    pub fn stats(&self) -> (u64, u64) {
        match &self.inner {
            Some(SendCell(i)) => {
                let iv = i.output.ivars();
                (iv.delivered.load(Ordering::Relaxed), iv.skipped.load(Ordering::Relaxed))
            }
            None => (0, 0),
        }
    }
}

fn shareable_content() -> Result<Retained<SCShareableContent>> {
    let (tx, rx) = mpsc::channel::<Result<SendCell<Retained<SCShareableContent>>, String>>();
    let block = RcBlock::new(move |content: *mut SCShareableContent, err: *mut NSError| {
        let r = if content.is_null() {
            let msg = if err.is_null() {
                "unknown error".to_string()
            } else {
                unsafe { &*err }.localizedDescription().to_string()
            };
            Err(msg)
        } else {
            // SAFETY: SCK hands us a live object for the duration of the callback.
            match unsafe { Retained::retain(content) } {
                Some(c) => Ok(SendCell(c)),
                None => Err("null content".into()),
            }
        };
        let _ = tx.send(r);
    });
    unsafe {
        SCShareableContent::getShareableContentExcludingDesktopWindows_onScreenWindowsOnly_completionHandler(
            false, true, &block,
        );
    }
    match rx.recv_timeout(Duration::from_secs(15)) {
        Ok(Ok(SendCell(c))) => Ok(c),
        Ok(Err(e)) => bail!("SCShareableContent failed: {e} (Screen Recording permission?)"),
        Err(_) => bail!("SCShareableContent timed out"),
    }
}

fn main_display(content: &SCShareableContent) -> Option<Retained<SCDisplay>> {
    let main_id = CGMainDisplayID();
    let displays: Retained<NSArray<SCDisplay>> = unsafe { content.displays() };
    let mut first = None;
    for i in 0..displays.count() {
        let d = displays.objectAtIndex(i);
        if unsafe { d.displayID() } == main_id {
            return Some(d);
        }
        if first.is_none() {
            first = Some(d);
        }
    }
    first
}

impl ScreenCapture for MacCapture {
    fn start(&mut self, max_fps: u32, on_frame: Box<dyn FnMut(Frame) + Send>) -> Result<CaptureInfo> {
        self.stop();
        let max_fps = max_fps.clamp(1, 240);

        let content = shareable_content()?;
        let display = main_display(&content).context("no display found")?;
        let filter = unsafe {
            SCContentFilter::initWithDisplay_excludingWindows(SCContentFilter::alloc(), &display, &NSArray::new())
        };

        let points_w = unsafe { display.width() } as f64;
        let points_h = unsafe { display.height() } as f64;
        let mut scale = unsafe { filter.pointPixelScale() } as f64;
        if !(scale.is_finite() && scale >= 1.0) {
            let px = CGDisplayPixelsWide(CGMainDisplayID()) as f64;
            scale = if points_w > 0.0 && px > 0.0 { px / points_w } else { 1.0 };
        }
        let width = ((points_w * scale).round() as u32) & !1;
        let height = ((points_h * scale).round() as u32) & !1;
        if width == 0 || height == 0 {
            bail!("display reports zero size");
        }

        let cfg = unsafe { SCStreamConfiguration::new() };
        unsafe {
            cfg.setWidth(width as usize);
            cfg.setHeight(height as usize);
            cfg.setShowsCursor(true);
            cfg.setMinimumFrameInterval(CMTime::new(1, max_fps as i32));
            cfg.setPixelFormat(kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange);
            cfg.setQueueDepth(5);
            cfg.setCapturesAudio(false);
        }

        let output = StreamOutput::new(width, height, on_frame);
        let delegate = ProtocolObject::from_ref(&*output);
        let stream = unsafe {
            SCStream::initWithFilter_configuration_delegate(SCStream::alloc(), &filter, &cfg, Some(delegate))
        };
        let queue = DispatchQueue::new("agent-snap.capture", DispatchQueueAttr::SERIAL);
        unsafe {
            stream
                .addStreamOutput_type_sampleHandlerQueue_error(
                    ProtocolObject::from_ref(&*output),
                    SCStreamOutputType::Screen,
                    Some(&queue),
                )
                .map_err(|e| anyhow!("addStreamOutput: {}", e.localizedDescription()))?;
        }

        let (tx, rx) = mpsc::channel::<Option<String>>();
        let block = RcBlock::new(move |err: *mut NSError| {
            let msg = (!err.is_null()).then(|| unsafe { &*err }.localizedDescription().to_string());
            let _ = tx.send(msg);
        });
        unsafe { stream.startCaptureWithCompletionHandler(Some(&block)) };
        match rx.recv_timeout(Duration::from_secs(10)) {
            Ok(None) => {}
            Ok(Some(e)) => bail!("startCapture failed: {e}"),
            Err(_) => bail!("startCapture timed out"),
        }

        log::info!("capture started {width}x{height} scale={scale} max_fps={max_fps}");
        self.inner = Some(SendCell(Inner { stream, output, _queue: queue }));
        Ok(CaptureInfo { width, height, scale })
    }

    fn stop(&mut self) {
        let Some(SendCell(inner)) = self.inner.take() else { return };
        let (tx, rx) = mpsc::channel::<()>();
        let block = RcBlock::new(move |_err: *mut NSError| {
            let _ = tx.send(());
        });
        unsafe { inner.stream.stopCaptureWithCompletionHandler(Some(&block)) };
        let _ = rx.recv_timeout(Duration::from_secs(3));
        if let Ok(mut g) = inner.output.ivars().cb.lock() {
            *g = None;
        }
        drop(inner);
    }
}

impl Drop for MacCapture {
    fn drop(&mut self) {
        self.stop();
    }
}
